//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agence.ServiceHotel {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceHotel.ServiceHotelSoap")]
    public interface ServiceHotelSoap {
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément idAgence de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsulterDisponibilité", ReplyAction="*")]
        Agence.ServiceHotel.ConsulterDisponibilitéResponse ConsulterDisponibilité(Agence.ServiceHotel.ConsulterDisponibilitéRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsulterDisponibilité", ReplyAction="*")]
        System.Threading.Tasks.Task<Agence.ServiceHotel.ConsulterDisponibilitéResponse> ConsulterDisponibilitéAsync(Agence.ServiceHotel.ConsulterDisponibilitéRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément idAgence de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Reserver", ReplyAction="*")]
        Agence.ServiceHotel.ReserverResponse Reserver(Agence.ServiceHotel.ReserverRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Reserver", ReplyAction="*")]
        System.Threading.Tasks.Task<Agence.ServiceHotel.ReserverResponse> ReserverAsync(Agence.ServiceHotel.ReserverRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsulterDisponibilitéRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsulterDisponibilité", Namespace="http://tempuri.org/", Order=0)]
        public Agence.ServiceHotel.ConsulterDisponibilitéRequestBody Body;
        
        public ConsulterDisponibilitéRequest() {
        }
        
        public ConsulterDisponibilitéRequest(Agence.ServiceHotel.ConsulterDisponibilitéRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsulterDisponibilitéRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string idAgence;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string mdpAgence;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int nbPers;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime dA;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.DateTime dD;
        
        public ConsulterDisponibilitéRequestBody() {
        }
        
        public ConsulterDisponibilitéRequestBody(string idAgence, string mdpAgence, int nbPers, System.DateTime dA, System.DateTime dD) {
            this.idAgence = idAgence;
            this.mdpAgence = mdpAgence;
            this.nbPers = nbPers;
            this.dA = dA;
            this.dD = dD;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsulterDisponibilitéResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsulterDisponibilitéResponse", Namespace="http://tempuri.org/", Order=0)]
        public Agence.ServiceHotel.ConsulterDisponibilitéResponseBody Body;
        
        public ConsulterDisponibilitéResponse() {
        }
        
        public ConsulterDisponibilitéResponse(Agence.ServiceHotel.ConsulterDisponibilitéResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsulterDisponibilitéResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Agence.ServiceHotel.ArrayOfString ConsulterDisponibilitéResult;
        
        public ConsulterDisponibilitéResponseBody() {
        }
        
        public ConsulterDisponibilitéResponseBody(Agence.ServiceHotel.ArrayOfString ConsulterDisponibilitéResult) {
            this.ConsulterDisponibilitéResult = ConsulterDisponibilitéResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReserverRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Reserver", Namespace="http://tempuri.org/", Order=0)]
        public Agence.ServiceHotel.ReserverRequestBody Body;
        
        public ReserverRequest() {
        }
        
        public ReserverRequest(Agence.ServiceHotel.ReserverRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReserverRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string idAgence;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string mdpAgence;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int numOffre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string nom;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.DateTime dA;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public System.DateTime dD;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int nbPers;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string prenom;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string numCarte;
        
        public ReserverRequestBody() {
        }
        
        public ReserverRequestBody(string idAgence, string mdpAgence, int numOffre, string nom, System.DateTime dA, System.DateTime dD, int nbPers, string prenom, string numCarte) {
            this.idAgence = idAgence;
            this.mdpAgence = mdpAgence;
            this.numOffre = numOffre;
            this.nom = nom;
            this.dA = dA;
            this.dD = dD;
            this.nbPers = nbPers;
            this.prenom = prenom;
            this.numCarte = numCarte;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReserverResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReserverResponse", Namespace="http://tempuri.org/", Order=0)]
        public Agence.ServiceHotel.ReserverResponseBody Body;
        
        public ReserverResponse() {
        }
        
        public ReserverResponse(Agence.ServiceHotel.ReserverResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReserverResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ReserverResult;
        
        public ReserverResponseBody() {
        }
        
        public ReserverResponseBody(string ReserverResult) {
            this.ReserverResult = ReserverResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceHotelSoapChannel : Agence.ServiceHotel.ServiceHotelSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceHotelSoapClient : System.ServiceModel.ClientBase<Agence.ServiceHotel.ServiceHotelSoap>, Agence.ServiceHotel.ServiceHotelSoap {
        
        public ServiceHotelSoapClient() {
        }
        
        public ServiceHotelSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceHotelSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceHotelSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceHotelSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Agence.ServiceHotel.ConsulterDisponibilitéResponse Agence.ServiceHotel.ServiceHotelSoap.ConsulterDisponibilité(Agence.ServiceHotel.ConsulterDisponibilitéRequest request) {
            return base.Channel.ConsulterDisponibilité(request);
        }
        
        public Agence.ServiceHotel.ArrayOfString ConsulterDisponibilité(string idAgence, string mdpAgence, int nbPers, System.DateTime dA, System.DateTime dD) {
            Agence.ServiceHotel.ConsulterDisponibilitéRequest inValue = new Agence.ServiceHotel.ConsulterDisponibilitéRequest();
            inValue.Body = new Agence.ServiceHotel.ConsulterDisponibilitéRequestBody();
            inValue.Body.idAgence = idAgence;
            inValue.Body.mdpAgence = mdpAgence;
            inValue.Body.nbPers = nbPers;
            inValue.Body.dA = dA;
            inValue.Body.dD = dD;
            Agence.ServiceHotel.ConsulterDisponibilitéResponse retVal = ((Agence.ServiceHotel.ServiceHotelSoap)(this)).ConsulterDisponibilité(inValue);
            return retVal.Body.ConsulterDisponibilitéResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Agence.ServiceHotel.ConsulterDisponibilitéResponse> Agence.ServiceHotel.ServiceHotelSoap.ConsulterDisponibilitéAsync(Agence.ServiceHotel.ConsulterDisponibilitéRequest request) {
            return base.Channel.ConsulterDisponibilitéAsync(request);
        }
        
        public System.Threading.Tasks.Task<Agence.ServiceHotel.ConsulterDisponibilitéResponse> ConsulterDisponibilitéAsync(string idAgence, string mdpAgence, int nbPers, System.DateTime dA, System.DateTime dD) {
            Agence.ServiceHotel.ConsulterDisponibilitéRequest inValue = new Agence.ServiceHotel.ConsulterDisponibilitéRequest();
            inValue.Body = new Agence.ServiceHotel.ConsulterDisponibilitéRequestBody();
            inValue.Body.idAgence = idAgence;
            inValue.Body.mdpAgence = mdpAgence;
            inValue.Body.nbPers = nbPers;
            inValue.Body.dA = dA;
            inValue.Body.dD = dD;
            return ((Agence.ServiceHotel.ServiceHotelSoap)(this)).ConsulterDisponibilitéAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Agence.ServiceHotel.ReserverResponse Agence.ServiceHotel.ServiceHotelSoap.Reserver(Agence.ServiceHotel.ReserverRequest request) {
            return base.Channel.Reserver(request);
        }
        
        public string Reserver(string idAgence, string mdpAgence, int numOffre, string nom, System.DateTime dA, System.DateTime dD, int nbPers, string prenom, string numCarte) {
            Agence.ServiceHotel.ReserverRequest inValue = new Agence.ServiceHotel.ReserverRequest();
            inValue.Body = new Agence.ServiceHotel.ReserverRequestBody();
            inValue.Body.idAgence = idAgence;
            inValue.Body.mdpAgence = mdpAgence;
            inValue.Body.numOffre = numOffre;
            inValue.Body.nom = nom;
            inValue.Body.dA = dA;
            inValue.Body.dD = dD;
            inValue.Body.nbPers = nbPers;
            inValue.Body.prenom = prenom;
            inValue.Body.numCarte = numCarte;
            Agence.ServiceHotel.ReserverResponse retVal = ((Agence.ServiceHotel.ServiceHotelSoap)(this)).Reserver(inValue);
            return retVal.Body.ReserverResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Agence.ServiceHotel.ReserverResponse> Agence.ServiceHotel.ServiceHotelSoap.ReserverAsync(Agence.ServiceHotel.ReserverRequest request) {
            return base.Channel.ReserverAsync(request);
        }
        
        public System.Threading.Tasks.Task<Agence.ServiceHotel.ReserverResponse> ReserverAsync(string idAgence, string mdpAgence, int numOffre, string nom, System.DateTime dA, System.DateTime dD, int nbPers, string prenom, string numCarte) {
            Agence.ServiceHotel.ReserverRequest inValue = new Agence.ServiceHotel.ReserverRequest();
            inValue.Body = new Agence.ServiceHotel.ReserverRequestBody();
            inValue.Body.idAgence = idAgence;
            inValue.Body.mdpAgence = mdpAgence;
            inValue.Body.numOffre = numOffre;
            inValue.Body.nom = nom;
            inValue.Body.dA = dA;
            inValue.Body.dD = dD;
            inValue.Body.nbPers = nbPers;
            inValue.Body.prenom = prenom;
            inValue.Body.numCarte = numCarte;
            return ((Agence.ServiceHotel.ServiceHotelSoap)(this)).ReserverAsync(inValue);
        }
    }
}
